# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-afcce86f-9e10-40fc-9c9f-36bc71a26a5a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-afcce86f-9e10-40fc-9c9f-36bc71a26a5a".device = "/dev/disk/by-uuid/afcce86f-9e10-40fc-9c9f-36bc71a26a5a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B25C-8BE4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3b5e812e-61c6-4c91-a7ac-903a2de5dbbc"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
